// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Directo (sin "-pooler"), no el pooled que usa la app en runtime — el
    // pooler de Neon (PgBouncer en modo transacción) no soporta bien los
    // advisory locks que usa `prisma migrate`. Ver .env, DATABASE_URL_UNPOOLED.
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
